### ISSUE TITLE
RuntimeError: cuDNN error: CUDNN_STATUS_EXECUTION_FAILED

### ISSUE THREAD

**Issue by gitty-gaurav** [nanoporetech/taiyaki#37]
Dear All,
With several attempts to run taiyaki/bin/train_mod_flipflop.py, I am ending up with an error related to cuDNN. Could you please help me resolve this? The error is as follows-
```
* Taiyaki version 4.1.0
* Command line
/home/gaurav/current_account/soft_scripts/ONT/taiyaki/bin/train_mod_flipflop.py --device 0 --mod_factor 0.01 --outdir training_walk_3 /home/gaurav/current_account/soft_scripts/ONT/taiyaki/models/mGru_cat_mod_flipflop.py intermediate_files/modbase_walk_3.hdf5 --overwrite
* Loading data from intermediate_files/modbase_walk_3.hdf5
* Per read file MD5 243a48f6886023013630f367d73be3eb
* Will train from all strands
* Loaded 5891 reads.
* Using alphabet definition: canonical alphabet ACGT with modified base(s) Y=6mA (alt to A), Z=5mC (alt to C)
* Sampled 1000 chunks: median(mean_dwell)=9.87, mad(mean_dwell)=0.86
* Reading network from /home/gaurav/current_account/soft_scripts/ONT/taiyaki/models/mGru_cat_mod_flipflop.py
1.0.0
Traceback (most recent call last):
  File "/home/gaurav/current_account/soft_scripts/ONT/taiyaki/bin/train_mod_flipflop.py", line 358, in <module>
    main()
  File "/home/gaurav/current_account/soft_scripts/ONT/taiyaki/bin/train_mod_flipflop.py", line 202, in main
    network = helpers.load_model(args.model, **model_kwargs).to(device)
  File "/usr/local/lib/python3.5/dist-packages/torch/nn/modules/module.py", line 381, in to
    return self._apply(convert)
  File "/usr/local/lib/python3.5/dist-packages/torch/nn/modules/module.py", line 187, in _apply
    module._apply(fn)
  File "/usr/local/lib/python3.5/dist-packages/torch/nn/modules/module.py", line 187, in _apply
    module._apply(fn)
  File "/usr/local/lib/python3.5/dist-packages/torch/nn/modules/module.py", line 187, in _apply
    module._apply(fn)
  File "/usr/local/lib/python3.5/dist-packages/torch/nn/modules/module.py", line 187, in _apply
    module._apply(fn)
  File "/usr/local/lib/python3.5/dist-packages/torch/nn/modules/rnn.py", line 118, in _apply
    self.flatten_parameters()
  File "/usr/local/lib/python3.5/dist-packages/torch/nn/modules/rnn.py", line 114, in flatten_parameters
    self.batch_first, bool(self.bidirectional))
RuntimeError: cuDNN error: CUDNN_STATUS_EXECUTION_FAILED

real	0m12.389s
user	0m16.438s
sys	0m14.909s
```
Additional info:
I have installed- CUDA v10.0.13, cuDNN v7.4.1 (compatibile with CUDA v10.0; also tried cuDNN v7.6.2), nvcc and python 2.7 and 3.5 are available system-wide. Graphic card- NVIDIA GEFORCE RTX-2080-Ti along with Nvidia driver v410.48. I have installed Taiyaki in venv as recommended and the 'make install' process successfully installs all the dependencies including pytorch v1.0.0 (which I believe is also associated with the error).  
I also believe that this could be an issue of incompatibilities between different versions of CUDA, cuDNN, Pytorch, Python, Nvidia driver and graphic card. Thus, it would also be helpful if anyone of you running Taiyaki successfully on NVIDIA GEFORCE RTX-2080-Ti graphic card can post versions of different dependencies mentioned above. Many thanks !

Best,
Gaurav

**Comment by tmassingham-ont** [comment]
Hello.  Your error message suggests that you are not using the version of PyTorch that Taiyaki should have installed in its virtual environment; have you definitely enabled the environment before running?  This is important since the standard version of PyTorch that is installed via `pip install` is not compatible with all versions of CUDA.

I am aware of two successful cases of Taiyaki running on 2080's

|  Card     |  Software  |  Version   |
|---------|---------|-----------|
| 2080 Ti | Taiyaki   | 4.1.0       |
|               | Driver    | 418.67    |
|               | CUDA    | 10.0.130 |
|               | PyTorch | 1.0.0       |
|               | (cudnn) | 7401 (*)  |
| Titan RTX | Taiyaki   | 4.1.0       |
|                  | Driver    | 418.39    |
|                  | CUDA    | 10.0.130 |
|                  | PyTorch | 1.0.0       |
|                  | (cudnn) | 7501 (*)  |

(*) as reported by `torch.backends.cudnn.version()` -- CuDNN was not installed on either machine independently from the PyTorch package.

The following commands may be useful to determine what versions PyTorch is actually using
```bash
source taiyaki/venv/bin/activate
python -c 'import taiyaki; print(taiyaki.__version__)'
python -c 'import torch; print(torch.__version__)'
python -c 'import torch; print(torch.version.cuda)'
python -c 'import torch; print(torch.backends.cudnn.version())'
python -c 'import torch; print(torch.backends.cudnn.enabled)'
```

**Comment by gitty-gaurav** [comment]
Dear Tim, thanks for your prompt reply. I confirm that I have enabled the environment before running the command-
`sudo nohup bash -c 'time ~/current_account/soft_scripts/ONT/taiyaki/bin/train_mod_flipflop.py --device 0 --mod_factor 0.01 --outdir training_walk_3 ~/current_account/soft_scripts/ONT/taiyaki/models/mGru_cat_mod_flipflop.py intermediate_files/modbase_walk_3.hdf5 --overwrite' &`

I agree that the standard version of pytorch installed outside of the environment is v1.1.0. However, the version of pytorch within environment (activated before command) is v1.0.0. I can assure this via three ways- 1) Your suggested commands 2) lookup at taiyaki/venv/lib/python3.5/site-package and 3) lookup at taiyaki/build/wheelhouse/10.0/ folder. The lookups and output of your suggested commands are as follows:  
![image](https://user-images.githubusercontent.com/44394743/62456734-6da58280-b779-11e9-8937-7ecd6b87a04c.png)

As the only difference I see as compared to our and your tried & tested version is regarding the Nvidia driver with v418. We could replace our v410 with v418 driver and re-try installing Taiyaki, but I doubt that will resolve. Let me know your thoughts. Thanks.

**Comment by tmassingham-ont** [comment]
Hi. The error you posted clearly shows at the PyTorch installation being used is that in `/usr/local/lib/python3.5/dist-packages/torch`. 

I think the issue here is`sudo` , it starts a new shell to run Taiyaki in and so is no longer in the virtual environment.  Running Taiyaki using `sudo` is not recommended and I strongly council against doing so unless absolutely necessary.  

If you must run Taiyaki as root, then the virtual environment needs to be activated after `sudo`, e.g.: `sudo nohup bash -c 'source taiyaki/venv/bin/activate ; time taiyaki/bin/train_mod_flipflop.py --device 0 --mod_factor 0.01 --outdir training_walk_3 taiyaki/models/mGru_cat_mod_flipflop.py intermediate_files/modbase_walk_3.hdf5 --overwrite'`

**Comment by gitty-gaurav** [comment]
Hi Tim, removing the sudo did the trick !
Many thanks for your advices.

Best, Gaurav
